# Generated by Django 4.0.2 on 2022-03-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_text', models.CharField(max_length=20, verbose_name='login')),
                ('password_text', models.CharField(max_length=200, verbose_name='password')),
                ('name_text', models.CharField(max_length=200, verbose_name='name')),
                ('surname_text', models.CharField(max_length=200, verbose_name='surname')),
                ('email_text', models.CharField(max_length=200, verbose_name='email')),
                ('date_reg', models.DateTimeField(verbose_name='date of registration')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_text', models.CharField(max_length=20, verbose_name='login')),
                ('password_text', models.CharField(max_length=200, verbose_name='password')),
                ('loggin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applic.registration')),
            ],
        ),
    ]
